repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    values:
      - service:
          type: LoadBalancer

  - name: argo-workflows
    namespace: argo
    chart: argo/argo-workflows
    version: 0.41.7
