repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

  - name: argo
    url: https://argoproj.github.io/argo-helm

  - name: mattermost
    url:  https://helm.mattermost.com

  #- name: bitnami
  #  url:  https://charts.bitnami.com/bitnami

  - name: oauth2-proxy
    url:  https://oauth2-proxy.github.io/manifests 

  - name: bitnami
    url:  https://charts.bitnami.com/bitnami

  - name: nuclio
    url:  https://nuclio.github.io/nuclio/charts

  - name: vector
    url:  https://helm.vector.dev

  - name: grafana
    url:  https://grafana.github.io/helm-charts

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 29.0.0
    values:
      - './traefik/values.yaml'

  - name: argo-workflows
    namespace: argo
    chart: argo/argo-workflows
    version: 0.41.7
    values:
      - './argo-workflows/values.yaml'

  - name: argo-workflows-ingressroute
    namespace: argo
    chart: './argo-workflows/chart/'
  
  - name: argo-cd
    namespace: argocd
    chart: argo/argo-cd
    values:
      - './argocd/values.yaml'
    
  - name: argo-cd-ingressroute
    namespace: argocd
    chart: './argocd/chart/'
  # - name: postgresql
  #  namespace: postgresql
  #  chart: oci://registry-1.docker.io/bitnamicharts/postgresql
  #  version: 15.5.20
  #  values:
  #    - './postgresql/values.yaml'

  - name: oauth2-proxy
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy

  - name: fiftyone
    namespace: fiftyone
    chart: 'fiftyone/chart'

  - name: cvat
    namespace: cvat
    chart: cvat/cvat/helm-chart
    # values: cvat/values.yaml

  - name: cvat-ingressroute
    namespace: cvat
    chart: cvat/chart


  # - name: mlflow
  #  namespace: mlflow
  #  chart: oci://registry-1.docker.io/bitnamicharts/mlflow
  #  version: 1.4.20
 

  #- name: postgresql
  #  namespace: postgresql
  #  chart: bitnami/postgresql 
  #  version: 15.5.20

  # - name: mattermost-team-edition
  #  namespace: mattermost
  # chart: mattermost/mattermost-team-edition
  #  values:
  #    - './mattermost/values.yaml'

