apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`my-cluster.com`) && PathPrefix(`/nginx`)
    kind: Rule
    services:
    - kind: Service
      name: nginx-service
      namespace: default
      port: 80
    middlewares:
    - name: stripprefix-nginx
      namespace: default

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-nginx

spec:
  stripPrefix:
    prefixes:
      - /nginx
