repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 29.0.0
    values:
      - './values.yaml'