rbac:
  create: true
  rules: 
  - resources: ["events"]
    verbs: ["list", "watch"]
  - resources: ["namespaces"]
    verbs: ["create", "delete"]
  - resources: ["pods"]
    verbs: ["create","delete","get"]
  - apiGroups: [""]
    resources: ["pods/attach","pods/exec"]
    verbs: ["get","create","patch","delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list"]
  - resources: ["secrets"]
    verbs: ["create","delete","get","update"]
  - resources: ["serviceaccounts"]
    verbs: ["get"]
  - resources: ["services"]
    verbs: ["create","get"]

